# Generated by Django 4.2.4 on 2023-09-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocid', models.CharField(max_length=20)),
                ('release_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=20)),
                ('correctedValue_amount', models.CharField(max_length=20)),
                ('correctedValue_currency', models.CharField(max_length=20)),
                ('enteredValue_amount', models.CharField(max_length=20)),
                ('enteredValue_currency', models.CharField(max_length=20)),
                ('contractPeriod_startDate', models.DateTimeField()),
                ('contractPeriod_endtDate', models.DateTimeField()),
                ('contractPeriod_maxExtentDate', models.IntegerField()),
                ('contractPeriod_durationInDays', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='FileData',
        ),
    ]
