# Generated by Django 4.2.4 on 2023-09-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0003_alter_awards_amount_alter_awards_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='amount',
            field=models.FloatField(),
        ),
    ]
