# Generated by Django 4.2.4 on 2023-09-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0006_alter_awards_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='amount',
            field=models.FloatField(),
        ),
    ]
