# Generated by Django 4.2.4 on 2023-09-13 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0008_alter_awards_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.DecimalValidator(10, 2)]),
        ),
    ]
