# Generated by Django 4.2.4 on 2023-09-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0011_alter_awards_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='contractPeriod_durationInDays',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='contractPeriod_endtDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='contractPeriod_maxExtentDate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='contractPeriod_startDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='correctedValue_amount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='correctedValue_currency',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='currency',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='description',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='enteredValue_amount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='enteredValue_currency',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='ocid',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='release_id',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='status',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='title',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
