# Generated by Django 4.2.4 on 2023-09-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0012_alter_awards_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='contractPeriod_startDate',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='date',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
