# Generated by Django 4.2.4 on 2023-09-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0014_alter_awards_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('ocid', models.CharField(max_length=600, null=True)),
                ('release_id', models.CharField(max_length=600, null=True)),
                ('id', models.CharField(max_length=600, primary_key=True, serialize=False)),
                ('awards_ID', models.CharField(max_length=600, null=True)),
                ('title', models.CharField(max_length=600, null=True)),
                ('description', models.CharField(max_length=600, null=True)),
                ('status', models.CharField(max_length=60, null=True)),
                ('contractPeriod_starDate', models.DateTimeField(null=True)),
                ('contractPeriod_endDate', models.DateTimeField(null=True)),
                ('contractPeriod_maxExtentDate', models.IntegerField(null=True)),
                ('contractPeriod_durationInDays', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('currency', models.CharField(max_length=60, null=True)),
                ('dateSigned', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lanzamiento',
            fields=[
                ('ocid', models.CharField(max_length=600, null=True)),
                ('id', models.CharField(max_length=600, primary_key=True, serialize=False)),
                ('initiationType', models.CharField(max_length=600, null=True)),
                ('buyer_id', models.CharField(max_length=600, null=True)),
                ('budget_name', models.FloatField(max_length=600, null=True)),
                ('language', models.CharField(max_length=600, null=True)),
                ('date', models.DateTimeField(max_length=600, null=True)),
                ('tag', models.CharField(max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('ocid', models.CharField(max_length=600, null=True)),
                ('release_id', models.CharField(max_length=600, null=True)),
                ('id', models.CharField(max_length=600, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=600, null=True)),
                ('description', models.CharField(max_length=600, null=True)),
                ('status', models.CharField(max_length=600, null=True)),
                ('procuringEntity_id', models.CharField(max_length=600, null=True)),
                ('procuringEntity_name', models.CharField(max_length=600, null=True)),
                ('value_amount', models.FloatField(max_length=600, null=True)),
                ('value_currency', models.CharField(max_length=20, null=True)),
                ('procurementMethod', models.CharField(max_length=60, null=True)),
                ('procurementMethodDetails', models.CharField(max_length=60, null=True)),
                ('mainProcurementCategory', models.CharField(max_length=60, null=True)),
                ('awardCriteria', models.CharField(max_length=60, null=True)),
                ('tenderPeriod_starDate', models.DateTimeField(null=True)),
                ('tenderPeriod_endDate', models.DateTimeField(null=True)),
                ('tenderPeriod_maxExtentDate', models.IntegerField(null=True)),
                ('tenderPeriod_durationInDays', models.IntegerField(null=True)),
                ('enquiryPeriod_startDate', models.DateTimeField(null=True)),
                ('enquiryPeriod_endDate', models.DateTimeField(null=True)),
                ('enquiryPeriod_maxExtentDate', models.DateTimeField(null=True)),
                ('enquiryPeriod_durationInDays', models.IntegerField(null=True)),
                ('hasEnquiries', models.CharField(max_length=20, null=True)),
                ('eligibilityCriteria', models.CharField(max_length=600, null=True)),
                ('awardperiod_startDate', models.DateTimeField(null=True)),
                ('awardperiod_endDate', models.DateTimeField(null=True)),
                ('awardperiod_maxExtentDate', models.DateTimeField(null=True)),
                ('awardPeriod_durationInDays', models.IntegerField(null=True)),
                ('numberOfTenderers', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('ocid', models.CharField(max_length=600, null=True)),
                ('id', models.CharField(max_length=600, primary_key=True, serialize=False)),
                ('rationale', models.CharField(max_length=600, null=True)),
                ('budget_id', models.FloatField(max_length=600, null=True)),
                ('budget_description', models.CharField(max_length=600, null=True)),
                ('budget_amount', models.FloatField(max_length=600, null=True)),
                ('budget_currency', models.CharField(max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provedores',
            fields=[
                ('ocid', models.CharField(max_length=600, null=True)),
                ('release_id', models.CharField(max_length=600, null=True)),
                ('awards_id', models.CharField(max_length=600, null=True)),
                ('id', models.CharField(max_length=600, primary_key=True, serialize=False)),
                ('name', models.FloatField(max_length=600, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Awards',
            new_name='Premios',
        ),
    ]
