# Generated by Django 4.2.4 on 2023-09-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0016_alter_contratos_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='contractPeriod_starDate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='dateSigned',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='premios',
            name='contractPeriod_durationInDays',
            field=models.IntegerField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='premios',
            name='contractPeriod_endtDate',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
