# Generated by Django 4.2.4 on 2023-09-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0017_alter_contratos_contractperiod_stardate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premios',
            name='contractPeriod_durationInDays',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='premios',
            name='contractPeriod_endtDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='premios',
            name='contractPeriod_startDate',
            field=models.DateTimeField(null=True),
        ),
    ]
