# Generated by Django 4.2.4 on 2023-09-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0018_alter_premios_contractperiod_durationindays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premios',
            name='contractPeriod_endtDate',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='premios',
            name='contractPeriod_startDate',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
