# Generated by Django 4.2.4 on 2023-09-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0022_alter_provedores_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='enquiryPeriod_endDate',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='enquiryPeriod_maxExtentDate',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='enquiryPeriod_startDate',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='tenderPeriod_starDate',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='premios',
            name='contractPeriod_endtDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='premios',
            name='contractPeriod_startDate',
            field=models.DateTimeField(null=True),
        ),
    ]
