# Generated by Django 4.2.4 on 2023-09-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0025_alter_premios_contractperiod_endtdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratos',
            old_name='contractPeriod_starDate',
            new_name='contractPeriod_startDate',
        ),
        migrations.AlterField(
            model_name='contratos',
            name='contractPeriod_endDate',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='premios',
            name='contractPeriod_endtDate',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='premios',
            name='contractPeriod_maxExtentDate',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='premios',
            name='contractPeriod_startDate',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
