# Generated by Django 4.2.4 on 2023-09-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0028_rename_awards_id_contratos_awardid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premios',
            name='contractPeriod_endDate',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='premios',
            name='contractPeriod_startDate',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
