# Generated by Django 4.2.4 on 2023-09-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0029_alter_premios_contractperiod_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premios',
            name='contractPeriod_durationInDays',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
