# Generated by Django 4.2.4 on 2023-09-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0030_alter_premios_contractperiod_durationindays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licitacion',
            old_name='tenderPeriod_starDate',
            new_name='tenderPeriod_startDate',
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='awardperiod_endDate',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='awardperiod_maxExtentDate',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='awardperiod_startDate',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='tenderPeriod_endDate',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='tenderPeriod_maxExtentDate',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
