# Generated by Django 4.2.4 on 2023-09-21 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0031_rename_tenderperiod_stardate_licitacion_tenderperiod_startdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licitacion',
            old_name='awardperiod_endDate',
            new_name='awardPeriod_endDate',
        ),
        migrations.RenameField(
            model_name='licitacion',
            old_name='awardperiod_maxExtentDate',
            new_name='awardPeriod_maxExtentDate',
        ),
        migrations.RenameField(
            model_name='licitacion',
            old_name='awardperiod_startDate',
            new_name='awardPeriod_startDate',
        ),
    ]
