# Generated by Django 4.2.4 on 2023-09-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0033_alter_licitacion_tenderperiod_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='tenderPeriod_startDate',
            field=models.DateTimeField(max_length=600, null=True),
        ),
    ]
