# Generated by Django 4.2.4 on 2023-09-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0035_alter_licitacion_tenderperiod_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='tenderPeriod_endDate',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
